alias cu='cleanup.py'
alias hbt='cd ~/.db/prj/habit-maker; ./habit_maker2.py ; cd -'
alias lbs='logbook-status.py'
alias t='task'
alias pwn='projects_without_next.py'
alias pwnp='projects_without_next.py | pclip'
