export PATH=$PATH:$HOME/.rvm/bin
export PATH=$HOME/.node/bin:$HOME/.bu.bin/bin:$HOME/.db/bin/stable:$HOME/.db/bin:$PATH
export PATH=$PATH:$HOME/.omega.bin/bin
export PATH=$PATH:$HOME/.bu.cards/bin
export PATH=$PATH:$HOME/.bu.bin/bin
export PATH=$PATH:$HOME/.git-radar
export PATH=/opt/php/bin:$PATH
export PATH=/opt/java/bin:$PATH
. ~/.bin_path
